### ISSUE TITLE
"Why does an assignment issue occur after the installation is complete?"

### ISSUE THREAD

**Issue by xingxingjiukunkun** [teamtomo/membrain-seg#71] opened 2024-06-22 06:36 UTC
(membrain) [SLURM:1166] emuser@gpu2:/public/apps/em/membrain-seg $ membrain
Traceback (most recent call last):
  File "/public/apps/em/yes/envs/membrain/bin/membrain", line 5, in 
    from membrain_seg.segmentation.cli import cli
  File "/public/apps/em/yes/envs/membrain/lib/python3.9/site-packages/membrain_seg/segmentation/cli/init.py", line 5, in 
    from .segment_cli import segment  # noqa: F401
  File "/public/apps/em/yes/envs/membrain/lib/python3.9/site-packages/membrain_seg/segmentation/cli/segment_cli.py", line 12, in 
    from ..segment import segment as _segment
  File "/public/apps/em/yes/envs/membrain/lib/python3.9/site-packages/membrain_seg/segmentation/segment.py", line 17, in 
    from .dataloading.memseg_augmentation import get_mirrored_img, get_prediction_transforms
  File "/public/apps/em/yes/envs/membrain/lib/python3.9/site-packages/membrain_seg/segmentation/dataloading/memseg_augmentation.py", line 18, in 
    from membrain_seg.segmentation.dataloading.transforms import (
  File "/public/apps/em/yes/envs/membrain/lib/python3.9/site-packages/membrain_seg/segmentation/dataloading/transforms.py", line 608, in 
    AxesShuffle = Compose(
  File "/public/apps/em/yes/envs/membrain/lib/python3.9/site-packages/monai/transforms/compose.py", line 251, in init
    self.set_random_state(seed=get_seed())
  File "/public/apps/em/yes/envs/membrain/lib/python3.9/site-packages/monai/transforms/compose.py", line 263, in set_random_state
    _transform.set_random_state(seed=self.R.randint(MAX_SEED, dtype="uint32"))
  File "/public/apps/em/yes/envs/membrain/lib/python3.9/site-packages/monai/transforms/transform.py", line 207, in set_random_state
    _seed = _seed % MAX_SEED
OverflowError: Python integer 4294967296 out of bounds for uint32

**Comment by GenevieveBuckley** [comment] 2024-06-24 03:33
Duplicate of https://github.com/teamtomo/membrain-seg/issues/70, this issue can be closed.

**Comment by LorenzLamm** [comment] 2024-06-26 07:55
Thanks for reporting this issue @xingxingjiukunkun. As mentioned, this is duplicate of  https://github.com/teamtomo/membrain-seg/issues/70 and hopefully is now resolved with https://github.com/teamtomo/membrain-seg/pull/72.

**Closed by LorenzLamm** 2024-06-26 07:55 UTC
